# This workflow will build a docker container, publish it to IBM Container Registry, and deploy it to IKS when there is a push to the "main" branch.
#
# To configure this workflow:
#
# 1. Ensure that your repository contains a Dockerfile
# 2. Setup secrets in your repository by going to settings: Create ICR_NAMESPACE and IBM_CLOUD_API_KEY
# 3. Change the values for the IBM_CLOUD_REGION, REGISTRY_HOSTNAME, IMAGE_NAME, IKS_CLUSTER, DEPLOYMENT_NAME, and PORT

name: Build and Deploy to IKS

on:
  push:
    branches: [ "main" ]

# Environment variables available to all jobs and steps in this workflow
env:
  GHCR_USERNAME: maopengwei
  GHCR_TOKEN: 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

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # Get chia-dotnet   
    - name: Get chia-dotnet
      run: |
        git clone --depth=1 -b chore_retry https://github.com/Chiabee/chia-dotnet.git
        rm -rf chia-dotnet/.git
        rm -rf ChatServer
    
    # Login to ghcr.io
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ env.GHCR_USERNAME }}
        password: ${{ env.GHCR_TOKEN }}
    
    # tag
    - name: tag
      run: |
        docker tag pawket_api ghcr.io/maopengwei/pawket_api:latest
        docker tag pawket_processer ghcr.io/maopengwei/pawket_processer:latest
    
    # Build the Docker image
    - name: Build with Docker
      run: |
        sudo docker push ghcr.io/maopengwei/pawket_api:latest
        sudo docker push ghcr.io/maopengwei/pawket_syncer:latest
    
    # Push the image to ghcr.io
    - name: Push the image to ghcr
      run: |
        docker pull ghcr.io/maopengwei/pawket_api:latest
        docker pull ghcr.io/maopengwei/pawket_syncer:latest
