
name: Build and Deploy to GHCR

on:
  push:
    branches: [ "main" ]

# Environment variables available to all jobs and steps in this workflow

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get chia-dotnet
      run: |
        git clone --depth=1 -b chore_retry https://github.com/Chiabee/chia-dotnet.git
        rm -rf chia-dotnet/.git
        rm -rf ChatServer
    - name: build
      run: |
       bash build-docker.sh
    - name: tag
      run: |
        docker tag pawket_api ghcr.io/${{ github.actor }}/pawket_api:latest
        docker tag pawket_syncer ghcr.io/${{ github.actor }}/pawket_syncer:latest
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}   
    - name: Push image to ghcr
      run: |
        sudo docker push ghcr.io/${{ github.actor }}/pawket_api:latest
        sudo docker push ghcr.io/${{ github.actor }}/pawket_syncer:latest
