
name: Build and Deploy to GHCR

on:
  push:
    branches: [ "main" ]
env:
  REGISTRY: ghcr.io
  api_image: pawket_api
  syncer_image: pawket_syncer

# Environment variables available to all jobs and steps in this workflow

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get chia-dotnet
      run: |
        git clone --depth=1 -b chore_retry https://github.com/Chiabee/chia-dotnet.git
        rm -rf chia-dotnet/.git
        rm -rf ChatServer

    - name: build
      run: |
       bash build-docker.sh

    - name: tag
      run: |
        docker tag ${{ env.api_image }} ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.api_image }}
        docker tag ${{ env.syncer_image }} ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.syncer_image }}
    
    - name: Login
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}   
    
    - name: Pus image to ghcr
      run: |
        sudo docker push ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.api_image }}
        sudo docker push ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.syncer_image }}
