
name: Build and Deploy to IKS

on:
  push:
    branches: [ "main" ]

# Environment variables available to all jobs and steps in this workflow

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    permissions: 
      packages: write
      deployments: write
      repository-projects: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Get chia-dotnet   
    - name: Get chia-dotnet
      run: |
        git clone --depth=1 -b chore_retry https://github.com/Chiabee/chia-dotnet.git
        rm -rf chia-dotnet/.git
        rm -rf ChatServer
    
    # Login to ghcr.io
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: maopengwei
        password: ${{ env.secrets.GHCR_TOKEN }}
        
    # build
    - name: build
      run: |
        bash build-docker.sh
    # tag
    - name: tag
      run: |
        docker tag pawket_api ghcr.io/maopengwei/pawket_api:latest
        docker tag pawket_syncer ghcr.io/maopengwei/pawket_syncer:latest
    
    # push the Docker image to ghcr
    - name: Push image to ghcr
      run: |
        sudo docker push ghcr.io/maopengwei/pawket_api:latest
        sudo docker push ghcr.io/maopengwei/pawket_syncer:latest
